# Generated by Django 3.1.7 on 2021-04-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_records',
            old_name='age',
            new_name='pub_date',
        ),
    ]
